var majors = [	
		"Accounting",
		"Agricultural and Food Business Economics",
		"Agricultural and Food Systems",
		"Agricultural Biotechnology",
		"Agricultural Education",
		"Agricultural Technology and Production Management",
		"Agriculture and Food Security",
		"Animal Sciences",
		"Anthropology",
		"Apparel Design, Merchandising, and Textiles",
		"Architectural Studies",
		"Art",
		"Asian Studies",
		"Athletic Training",
		"Basic Medical Sciences",
		"Biochemistry",
		"Bioengineering",
		"Biology",
		"Chemical Engineering",
		"Chemistry",
		"Chinese",
		"Civil Engineering",
		"Communication and Society",
		"Comparative Ethnic Studies",
		"Computer Engineering",
		"Computer Science",
		"Construction Management",
		"Criminal Justice",
		"Digital Technology and Culture",
		"Economic Sciences",
		"Electrical Engineering",
		"Elementary Education",
		"English",
		"Entrepreneurship",
		"Environmental and Ecosystem Sciences",
		"Geology (Earth Sciences)",
		"Field Crop Management",
		"Finance",
		"Fine Arts",
		"Food Science",
		"Foreign Languages",
		"Forestry",
		"French",
		"Fruit and Vegetable Management",
		"Genetics and Cell Biology",
		"Social Sciences: General Studies",
		"History",
		"Hospitality Business Management",
		"Human Development",
		"Humanities: General Studies",
		"Integrated Plant Sciences",
		"Interior Design",
		"International Business",
		"Journalism and Media Production",
		"Landscape Architecture",
		"Landscape, Nursery, and Greenhouse Management",
		"Management",
		"Management Information Systems",
		"Marketing",
		"Materials Science and Engineering",
		"Mathematics",
		"Mechanical Engineering",
		"Microbiology",
		"Music",
		"Music Composition",
		"Music Education",
		"Music Performance",
		"Neuroscience",
		"Nursing (BSN)",
		"Nursing (RN to BSN)",
		"Nutrition and Exercise Physiology",
		"Organic Agriculture Systems",
		"Philosophy",
		"Physics",
		"Political Science",
		"Psychology",
		"Social Sciences: General Studies",
		"Social Studies Teaching",
		"Sociology",
		"Spanish",
		"Speech and Hearing Sciences",
		"Sport Management",
		"Sport Science",
		"Strategic Communication",
		"Turfgrass Management",
		"Winemaking (Viticulture and Enology)",
		"Zoology"
]





